name: Show differences in Maven property evaluation
on: [push]
jobs:
  demo-maven-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Install Maven 3
        run: |
          mkdir -p ~/temp ~/test-bin
          cd ~/temp
          wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz -O maven3.tgz
          tar xvf maven3.tgz
          ln -s apache-maven-3.9.9/bin/mvn ~/test-bin/mvn3
          ~/test-bin/mvn3 --version
      - name: Install Maven 4
        run: |
          mkdir -p ~/temp ~/test-bin
          cd ~/temp
          wget https://dlcdn.apache.org/maven/maven-4/4.0.0-rc-1/binaries/apache-maven-4.0.0-rc-1-bin.tar.gz -O maven4.tgz
          tar xvf maven4.tgz
          ln -s apache-maven-4.0.0-rc-1/bin/mvn ~/test-bin/mvn4
          ~/test-bin/mvn4 --version
      - name: Checkout repository
        uses: action/checkout@v4
